import std/os

mode = ScriptMode.Verbose

packageName = "threadspawn"
version = "0.1.0"
author = "durability-labs"
description = "Cancellation-safe primitives bridging taskpools thread spawn to Chronos async"
license = "Apache License 2.0 or MIT"

requires "nim >= 2.0.14", "chronicles >= 0.12.0 & < 0.13.0",
  "chronos >= 4.0.4 & < 4.1.0", "questionable >= 0.10.15 & < 0.11.0",
  "results", "taskpools >= 0.0.5", "threading >= 0.2.1 & < 0.3.0",
  "asynctest >= 0.5.2 & < 0.6.0", "unittest2 >= 0.2.3 & < 0.3.0",
  # chronicles pulls testutils unconstrained; 0.8.x fails to build
  # (fuzzing_engines imports results, undeclared in its nimble)
  "testutils >= 0.5.0 & < 0.6.0"

task test, "Run tests":
  # --skipParentCfg:on: when vendored inside another tree (archivist), Nim
  # walks parent dirs for config.nims and would pick up the host project's
  # config. Deps resolve via the nimble.paths file generated by nimble setup.
  if not fileExists("nimble.paths"):
    exec "nimble setup -y"
  exec "nim c -r --skipParentCfg:on --path:\".\" " & readFile("nimble.paths").replace("\n", " ") & " tests/testall.nim"

task format, "Format code using NPH":
  exec "nimble install https://github.com/durability-labs/nph@#version-0-6-2-prerelease"
  exec findExe("nph") & " threadspawn.nim tests/"
